Update delete-merged-branches.yml

diff --git a/.github/workflows/delete-merged-branches.yml b/.github/workflows/delete-merged-branches.yml
--- a/.github/workflows/delete-merged-branches.yml
+++ b/.github/workflows/delete-merged-branches.yml
@@ -28,6 +28,7 @@ jobs:
       - name: Delete merged branches
         run: |
           error_messages=""
+          set +e  # Disable exit on error
           while read branch; do
             if [ "$branch" != "main" ]; then
               output=$(git push origin --delete "$branch" 2>&1)
@@ -40,6 +41,7 @@ jobs:
               fi
             fi
           done < merged_branches.txt
+          set -e  # Re-enable exit on error
           if [ -n "$error_messages" ]; then
             echo -e "Error(s) encountered during branch deletion:\n$error_messages"
           fi
@@ -51,6 +53,7 @@ jobs:
       - name: Delete closed branches
         run: |
           error_messages=""
+          set +e  # Disable exit on error
           while read branch; do
             if [ "$branch" != "main" ]; then
               output=$(git push origin --delete "$branch" 2>&1)
@@ -63,6 +66,7 @@ jobs:
               fi
             fi
           done < closed_branches.txt
+          set -e  # Re-enable exit on error
           if [ -n "$error_messages" ]; then
             echo -e "Error(s) encountered during branch deletion:\n$error_messages"
           fi
